# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='articulos'),
        ),
    ]
