# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_auto_20170416_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole('reader'), gdstorage.storage.GoogleDrivePermissionType('user'), 'truekeros.colombia@gmail.com'),)), upload_to='articulo'),
        ),
    ]
