# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_auto_20170522_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='number',
            field=models.CharField(max_length=15, null=None),
        ),
    ]
